title:            Bivore
url:              http://butterwick.github.io/bivore.com/com
permalink:        pretty
pygments:         true
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
timezone:         Europe/London
paginate: 5
links: 
  - name:         About
    url:          /about
