title:            Bivore
url:              www.bivore.com
baseurl:          /
permalink:        pretty
pygments:         true
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
timezone:         Europe/London
paginate: 5
links: 
  - name:         About
    url:          /about
