title:            Mu-An Chiou - @muanchiou || @muan
url:              /Users/abutterw/Desktop/muan.github.com-3.0.0-none/_site
permalink:        pretty
pygments:         true
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
google_analytics: UA-21332781-7
timezone:         Europe/London
paginate: 5
links: 
  - name:         About
    url:          /about